name: Super-Linter

on: 
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master
      - develop

jobs:
  super-lint:
    name: Lint code base
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions@v3
        
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
